EP.FamilyTask/Models/Address/AddresFields.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EP.Nikolina_Marina.Models.Address
{
    public class AddresFields
    {
        [DisplayName("Ime")]
        public string CHRISTIANNAME { get; set; }

        [DisplayName("Prezime")]
        public string NAME { get; set; }

        [DisplayName("Id")]
        [Key] public string GGUID { get; set; }

        [DisplayName("Ulica")]
        public string GWSTATE1 { get; set; }

        [DisplayName("Broj")]
        public string GWSTATE2 { get; set; }

        [DisplayName("Poštanski broj i Grad")]
        public string GWSTATE3 { get; set; }

        public string GWBRANCH { get; set; }
    }
}

EP.FamilyTask/Models/Address/AddressModel.cs
namespace EP.Nikolina_Marina.Models.Address
{
    public class AddressModel
    {
        public string ObjectType { get; set; }

        public string Id { get; set; }

        public AddresFields Fields { get; set; }

        public Links Links { get; set; }
    }
}

EP.FamilyTask/Models/Address/Details/FamilyMemberDetailsFields.cs
using System;

namespace EP.Nikolina_Marina.Models.Address.Details
{
    public class FamilyMemberDetailsFields
    {
        public string GWBRANCH { get; set; }
        public bool BIRTHDAYGREETINGS { get; set; }
        public int BLOCKED_EMAILS { get; set; }
        public int CBADDRESS { get; set; }
        public int CBFAX1 { get; set; }
        public int CBFAX2 { get; set; }
        public int CBFAX3 { get; set; }
        public int CBIM { get; set; }
        public int CBMAIL { get; set; }
        public int CBPHONE1 { get; set; }
        public int CBPHONE2 { get; set; }
        public int CBPHONE3 { get; set; }
        public int CBWEB { get; set; }
        public string CHRISTIANNAME { get; set; }
        public bool CHRISTMASGREETINGS { get; set; }
        public string COMPNAME { get; set; }
        public int FOREIGNEDITPERMISSION { get; set; }
        public string GEOCODESTATUS { get; set; }
        public int GEOCODESTATUSNUMBER { get; set; }
        public string GGUID { get; set; }
        public string GWADDRESSFORMAT { get; set; }
        public bool GWDEACTIVATED { get; set; }
        public string GWSTATE1 { get; set; }
        public string GWSTATE2 { get; set; }
        public string GWSTATE3 { get; set; }
        public bool GWDUPLICATECHECK { get; set; }
        public bool GWIDENTITYEXIST { get; set; }
        public bool GWISCOMPANY { get; set; }
        public bool GWISCONTACT { get; set; }
        public bool GWISEMPLOYEE { get; set; }
        public bool GWISEXTERNALEMPLOYEE { get; set; }
        public bool GWKEEPCONTACTSYNCHRON { get; set; }
        public string GWPHONETIC_CHRISTIANNAME { get; set; }
        public string GWPHONETIC_COMPNAME { get; set; }
        public string GWPHONETIC_NAME { get; set; }
        public bool GWSSERVICEPASSWORDSET { get; set; }
        public bool HDBLOCKEDFORSUPPORT { get; set; }
        public DateTime INSERTTIMESTAMP { get; set; }
        public string INSERTUSER { get; set; }
        public int INXMAIL_BOUNCES { get; set; }
        public string NAME { get; set; }
        public string OWNERGUID { get; set; }
        public string OWNERNAME { get; set; }
        public DateTime UPDATETIMESTAMP { get; set; }
        public string UPDATEUSER { get; set; }
    }
}

EP.FamilyTask/Models/Address/Details/FullFamilyMemberModel.cs
namespace EP.Nikolina_Marina.Models.Address.Details
{
    public class FullFamilyMemberModel
    {
        public string ObjectType { get; set; }

        public string Id { get; set; }

        public FamilyMemberDetailsFields Fields { get; set; }

        public Links Links { get; set; }
    }
}

EP.FamilyTask/Models/Address/ExtendedAddreFields.cs
namespace EP.Nikolina_Marina.Models.Address
{
    public class ExtendedAddreFields : AddresFields
    {
        public string Etag { get; set; }
    }
}

EP.FamilyTask/Models/ErrorViewModel.cs
namespace EP.Nikolina_Marina.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EP.FamilyTask/Models/Links.cs
namespace EP.Nikolina_Marina.Models
{
    public class Links
    {
        public string Self { get; set; }

        public string Dossier { get; set; }
    }
}

EP.FamilyTask/Controllers/AddressController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using EP.Nikolina_Marina.Interfaces;
using EP.Nikolina_Marina.Models.Address;
using Microsoft.AspNetCore.Mvc;

namespace EP.Nikolina_Marina.Controllers
{
    public class AddressController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IAddressService _service;

        public AddressController(IAddressService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        // GET: FamilyMembers
        public async Task<IActionResult> Index()
        {
            var response = await _service.GetMembersAsync();

            return View(response.Select(x => x.Fields));
        }

        // GET: FamilyMembers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetMemberAsync(id);

            if (response == null) return NotFound();

            return View(response);
        }

        // GET: FamilyMembers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FamilyMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CHRISTIANNAME,NAME,GGUID,COMPNAME,GWSTATE1,GWSTATE2,GWSTATE3")]
            AddresFields addresFields)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateMemberAsync(addresFields);
                return RedirectToAction(nameof(Index));
            }

            return View(addresFields);
        }

        // GET: FamilyMembers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetMemberAsync(id);

            if (response == null) return NotFound();

            TempData["Etag"] = response.Etag;

            return View(response);
        }

        // POST: FamilyMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CHRISTIANNAME,NAME,GGUID,COMPNAME,GWSTATE1,GWSTATE2,GWSTATE3")]
            AddresFields addresFields)
        {
            if (id != addresFields.GGUID) return NotFound();

            if (ModelState.IsValid)
            {
                var model = _mapper.Map<AddresFields, ExtendedAddreFields>(addresFields);
                model.Etag = TempData["Etag"].ToString();

                await _service.UpdateMemberAsync(model);

                return RedirectToAction(nameof(Index));
            }

            return View(addresFields);
        }

        // GET: FamilyMembers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetMemberAsync(id);

            if (response == null) return NotFound();

            return View(response);
        }

        // POST: FamilyMembers/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _service.DeleteMemberAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

EP.FamilyTask/Controllers/HomeController.cs
using System.Diagnostics;
using EP.Nikolina_Marina.Models;
using Microsoft.AspNetCore.Mvc;

namespace EP.Nikolina_Marina.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EP.FamilyTask/Views/Address/Create.cshtml
@model EP.Nikolina_Marina.Models.Address.AddresFields

@{
    ViewData["Title"] = "Dodaj";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CHRISTIANNAME" class="control-label"></label>
                <input asp-for="CHRISTIANNAME" class="form-control" />
                <span asp-validation-for="CHRISTIANNAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NAME" class="control-label"></label>
                <input asp-for="NAME" class="form-control" />
                <span asp-validation-for="NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE1" class="control-label"></label>
                <input asp-for="GWSTATE1" class="form-control" />
                <span asp-validation-for="GWSTATE1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE2" class="control-label"></label>
                <input asp-for="GWSTATE2" class="form-control" />
                <span asp-validation-for="GWSTATE2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE2" class="control-label"></label>
                <input asp-for="GWSTATE2" class="form-control" />
                <span asp-validation-for="GWSTATE2" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EP.FamilyTask/Views/Address/Delete.cshtml
@model EP.Nikolina_Marina.Models.Address.AddresFields

@{
    ViewData["Title"] = "Brisanje";
}

<h1>Brisanje</h1>

<h3>Da li ste sigurni?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CHRISTIANNAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CHRISTIANNAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE3)
        </dd>
    
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GGUID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EP.FamilyTask/Views/Address/Details.cshtml
@model EP.Nikolina_Marina.Models.Address.AddresFields

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CHRISTIANNAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CHRISTIANNAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GWSTATE3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GWSTATE3)
        </dd>
   
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GGUID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EP.FamilyTask/Views/Address/Edit.cshtml
@model EP.Nikolina_Marina.Models.Address.AddresFields

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CHRISTIANNAME" class="control-label"></label>
                <input asp-for="CHRISTIANNAME" class="form-control" />
                <span asp-validation-for="CHRISTIANNAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NAME" class="control-label"></label>
                <input asp-for="NAME" class="form-control" />
                <span asp-validation-for="NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE1" class="control-label"></label>
                <input asp-for="GWSTATE1" class="form-control" />
                <span asp-validation-for="GWSTATE1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE2" class="control-label"></label>
                <input asp-for="GWSTATE2" class="form-control" />
                <span asp-validation-for="GWSTATE2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GWSTATE3" class="control-label"></label>
                <input asp-for="GWSTATE3" class="form-control" />
                <span asp-validation-for="GWSTATE3" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="GGUID" />
          
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EP.FamilyTask/Views/Address/Index.cshtml
@model IEnumerable<EP.Nikolina_Marina.Models.Address.AddresFields>

@{
    ViewData["Title"] = "Adrese";
}

<h1>Lista adresa</h1>

<p>
    <a asp-action="Create">Dodaj</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CHRISTIANNAME)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NAME)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.GWSTATE1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GWSTATE2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GWSTATE3)
            </th>
         
        
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CHRISTIANNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GWSTATE1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GWSTATE2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GWSTATE3)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GGUID">Uredi</a> |
                <a asp-action="Details" asp-route-id="@item.GGUID">Detalji</a> |
                <a asp-action="Delete" asp-route-id="@item.GGUID">Izbriši</a>
            </td>
        </tr>
}
    </tbody>
</table>

EP.FamilyTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Početna";
}

<div class="text-center">
    <h1 class="display-4">Dobrodošli</h1>
</div>

EP.FamilyTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EP.Nikolina Marina - Adrese</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Elektroničko poslovanje</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Address" asp-action="Index">Adrese</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - EP.Nikolina I Marina - Adrese - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", false)
</body>
</html>